#!/usr/bin/env bash
# Bash script to Install and configure HAproxy on your lb-01 server.
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo chown -R ubuntu /etc/haproxy
sudo echo "
frontend web-frontend
        bind *:80
        mode http
        default_backend web-backend
backend web-backend
        balance roundrobin
        server 30186-web-01 100.26.169.211:80 check
        server 30186-web-02 3.85.54.28:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
