#!/usr/bin/env bash
# Displays the time for 12 horus and 59 mins. Displays hs from 0 to 12 Displays mins from 1 to 59

hr=0

while [ $hr -le 12 ]
do
  echo "Hour: $hr"
  min=1
  while [ $min -le 59 ]
  do
    echo "$min"
    (( min++ ))
  done
  (( hr++ ))
done
